### ISSUE TITLE
济州自由行

### ISSUE THREAD

**Issue by fly0o0** [fly0o0/blog#43]
### 第一天行程：（中区：济州）
1. 12:40杭州到15:05济州岛
2. 出机场
3. 去济州宾馆
4. 山君不离（不一定有时间去）， 如果没时间就考虑去免税店
### 第二天行程：（中区：济州）
1. 7：00起床爬汉拿山
2. 下午差不多结束汉拿山，
3. 逛小火车公园或者love land
4. 准备去城山宾馆
### 第三天行程：（东区：城山）
1. 7点早起去日出峰，
2. 回来准备去牛岛，
3. 牛岛回来去涉地可支
4. 晚上回济州宾馆
### 第四天行程：（南区：西归浦）
1. 10点起床去中文区，泰迪熊博物馆
2. 如果有时间去看下正房瀑布或者偶来小路
3. 回程去宾馆拿寄存的行李
4. 去机场赶飞机

北区（济州）：
山君不离

东区：
龙头岩（不去，旅游团人太多）

第一天下午：
涉地可支

第二天：
城山日出峰
牛岛

南区（西归浦）：
柱状节理带
偶来小路

以下景点都是我们没去但听去过的人说，不去挺后悔，去了更后悔！
传说中的 "来都来了" 系列景点：
龙头岩，独立岩：大部分旅行团都会安排的景点，原因很简单，就是不要钱！都是坑爹的海边一块大石头！
城邑民俗村 ：名字听起来是不是很熟悉，就是我大天朝的购物"土家寨"之流，电视购物介绍的现场。你是买呢还是不买呢？
XXXX博物馆：（除了雪绿茶博物馆，小怡去过比较推荐之外）其它博物馆就是12岁以下年龄的人适合，因为只是让你拍拍照而已，门票还不便宜！多在8000韩元左右，要知道日出峰门票才2000韩元（去得早看日出根本不要钱~），而且大部分自然景点没有门票。
柱状节理带：火山石堆积在海边的模样，去过牛岛之后看啥海边都瞧不上了。
XXXX瀑布：必须去的是时候！比如夏天，比如大雨过后，才能看到，否则就是石头上流下一点水而已。而且规模肯定不如我大天朝的瀑布。若非要尝试，建议不要期待太高。
神奇之路： 这也叫景点吗？！一个上坡路车子放空挡能往坡上溜，特别去这里的话只能说明你是一个24k纯蠢货...

作者：甜菜迷妹
链接：https://www.zhihu.com/question/21444780/answer/104870386
来源：知乎
著作权归作者所有，转载请联系作者获得授权。

**Comment by chuge** [comment]
https://lvyou.baidu.com/jizhoudao/
